server:
  port: 8080
  servlet:
    context-path: /stucalendar

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/calendar?characterEncoding=UTF-8
    username: root
    password: 123456

  web:
    resources:
      static-locations:classpath:/static/,file:${photo.file.dir}



mybatis:
  type-aliases-package: com.wz.stucalendar.entity
  mapper-locations: classpath:mapper/*.xml

